
version: 2

models:
  - name: dim_patients
    description: "patients dimension table"
    columns:
      - name: gender
        description: "Gender of patient"
        tests:
          - unique
          - not_null

  - name: fact_patient_visits
    description: "A table for all patients visits"
    columns:
      - name: sitecode
        description: "unique identifier of a facility"
        tests:
          - not_null
